name: Run Lint

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y portaudio19-dev python3-pyaudio

      - name: Install uv
        uses: astral-sh/setup-uv@v5


      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Run Ruff
        run: uv run ruff check src/

      - name: Run Black
        run: uv run black --check src/

      - name: Run isort
        run: uv run isort --check-only src/